## welcome to numpy tutorial 

In [2]:
import numpy as np

In [3]:
myarray=np.array([3,6,8,9,6])

In [4]:
myarray

array([3, 6, 8, 9, 6])

In [5]:
myarray[0]

3

In [6]:
myarray[1:3]

array([6, 8])

In [7]:
myarray.dtype

dtype('int32')

## Array creation : conversion from other python structures


In [8]:
listarray=np.array([[1,2,3],[3,4,77],[6,9,4]])

In [9]:
listarray

array([[ 1,  2,  3],
       [ 3,  4, 77],
       [ 6,  9,  4]])

In [10]:
listarray.shape

(3, 3)

In [11]:
listarray.size

9

In [12]:
np.array({34,45,67})

array({34, 67, 45}, dtype=object)

In [13]:
zeros=np.zeros((2,5,6))

In [14]:
zeros

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [15]:
zeros.shape


(2, 5, 6)

In [16]:
zeros.size

60

In [17]:
arange=np.arange(50)

In [18]:
arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [19]:
arange=np.arange(50,10)

In [20]:
arange

array([], dtype=int32)

In [21]:
linspace=np.linspace(1,50,10)

In [22]:
linspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [23]:
emp=np.empty((4,6))

In [24]:
emp

array([[6.01347002e-154, 3.09540936e+169, 7.35419734e+223,
        2.11776155e+161, 1.46921998e+195, 6.15347528e+223],
       [2.68763563e-260, 6.12486778e+257, 6.01346954e-154,
        1.18600496e-259, 6.68153149e+151, 7.72493424e+228],
       [7.60357593e+179, 2.39803533e-258, 6.01347002e-154,
        1.14323016e+243, 1.06314419e+248, 5.98181658e-154],
       [3.32653124e-111, 1.53446210e-253, 2.64089007e-313,
        2.00886795e-308, 1.33360296e+241, 2.54354328e+151]])

In [25]:
emp_like=np.empty_like(linspace)

In [26]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [27]:
ide=np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr= np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.shape

(99,)

In [35]:
x=[[2,3,4],[4,5,6],[7,3,1]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[2, 3, 4],
       [4, 5, 6],
       [7, 3, 1]])

In [38]:
ar.sum(axis=0)

array([13, 11, 11])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)

2
3
4
4
5
6
7
3
1


In [ ]:
ar.ndim

2

In [ ]:
ar.nbytes

36

In [ ]:
one=np.array([2,3,4,5,69])

In [ ]:
one.argmax()

4